### ISSUE TITLE
Cannot measure distance between world1 and world2

### ISSUE THREAD

**Issue by ghost** [mics8128/NoMoreESP#5]
The log file was filled with this message. Could you please fix this?

```
java.lang.IllegalArgumentException: Cannot measure distance between world1 and world2
    at org.bukkit.Location.distanceSquared(Location.java:456)
    at org.bukkit.Location.distance(Location.java:439)
    at tw.mics.spigot.plugin.nomoreesp.runnable.CheckHideEntityRunnable.run(CheckHideEntityRunnable.java:35)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by mics8128** [comment]
is this happen very often?
or just very less?

witch NoMoreESP version you used.

**Comment by ghost** [comment]
It seems to happen when a player teleports to another world.

NoMoreESP version: 2.0.1

**Comment by mics8128** [comment]
OK, i will check about it.
